### ISSUE TITLE
能否添加邮件通知功能

### ISSUE THREAD

**Issue by weloe** [Rock-Candy-Tea/hexo-webpushr-notification#10]
webpushr有个订阅收集邮件的功能
![image](https://github.com/Rock-Candy-Tea/hexo-webpushr-notification/assets/87379877/1d81a14c-cb9a-48d2-8463-4ad7f64fddc8)

能否配合这个功能实现邮件推送？

**Comment by CCKNBC** [comment]
据我的理解，他收集手机和邮箱，应该是为了收集用户信息，得到用户表，然后导出后通过其他服务去给客户发送广告之类的。
我还没找到有对应的 API 接口能联系到这个邮箱获取
