### ISSUE TITLE
感谢提供这么棒的hexo推送插件

### ISSUE THREAD

**Issue by xiyuvi** [Rock-Candy-Tea/hexo-webpushr-notification#2]
请教一下,其他主题可以直接使用吗,我用的是fluid主题.
还有就是,我在博客评论报错了,您的博客可能有问题
![image](https://user-images.githubusercontent.com/38217058/202146573-45fd4ca3-1683-425d-9bde-0004f3dade33.png)

**Comment by CCKNBC** [comment]
评论可能是Waline或Leancloud那边出问题了
然后这个插件应该是能在其他主题使用的

**Comment by xiyuvi** [comment]
> 评论可能是Waline或Leancloud那边出问题了 然后这个插件应该是能在其他主题使用的

感谢分享,求大佬出这个配置,小博客没有那么多分类,还是希望可以向所有用户推送文章（目前根据个人需求是这个设置，默认行为为当未匹配到对应分类时不推送文章，而不是向所有用户推送文章，后续可能会提供配置）

**Comment by CCKNBC** [comment]
稍作修改就好了，因为其实这个插件更偏向自用，一开始没打算适配那么多，我晚上看一下

**Comment by xiyuvi** [comment]
> 稍作修改就好了，因为其实这个插件更偏向自用，一开始没打算适配那么多，我晚上看一下

谢谢大佬，麻烦您有时间看看

**Comment by CCKNBC** [comment]
> > 稍作修改就好了，因为其实这个插件更偏向自用，一开始没打算适配那么多，我晚上看一下
> 
> 谢谢大佬，麻烦您有时间看看

已支持，请安装最新版，并按照README新增配置即可 https://www.npmjs.com/package/hexo-webpushr-notification

**Comment by xiyuvi** [comment]
> > > 稍作修改就好了，因为其实这个插件更偏向自用，一开始没打算适配那么多，我晚上看一下
> > 
> > 
> > 谢谢大佬，麻烦您有时间看看
> 
> 已支持，请安装最新版，并按照README新增配置即可 https://www.npmjs.com/package/hexo-webpushr-notification

谢谢大佬，我更新了，配置后不能自动推送 我再照着文档看一下

**Comment by CCKNBC** [comment]
已更新，如有问题请及时反馈，菜鸡只会写bug

**Comment by xiyuvi** [comment]
> 已更新，如有问题请及时反馈，菜鸡只会写bug

感谢 0.0 我再试一试
