### ISSUE TITLE
我这个工作流现在能正常执行下去了，但是好像因为先把更新推送到了仓库，然后再验证 本地 与 在线 文章信息是否一致，导致他一直是验证结果一致

### ISSUE THREAD

**Issue by xiyuvi** [Rock-Candy-Tea/hexo-webpushr-notification#3]
![image](https://user-images.githubusercontent.com/38217058/205194890-875ac62e-f881-46d5-aa14-77b1edcd3b9f.png)
我这个工作流现在能正常执行下去了，但是好像因为先把更新推送到了仓库，然后再验证 本地 与 在线 文章信息是否一致，导致他一直是验证结果一致，您的hexo仓库是哪个呀，我去看看你的工作流程，我看你只有四个仓库，都不是hexo 0.0

**Comment by xiyuvi** [comment]
我看到仓库了，昨天是我眼瞎了 ..

**Comment by CCKNBC** [comment]
因为源仓库就那么写的，我晚上把`hexo.on("deployAfter")改成deployBefore`应该就好了

**Comment by CCKNBC** [comment]
主要是我自己没有用插件部署，所以其实也没发现这个问题，毕竟我的推送在后面手写的😂

**Comment by CCKNBC** [comment]
改完应该就能发布0.1.0正式版了，希望没什么问题了

**Comment by CCKNBC** [comment]
已发布，未测试

**Comment by xiyuvi** [comment]
> 已发布，未测试

![image](https://user-images.githubusercontent.com/38217058/205239840-17f9412c-267b-46e5-91b0-04bb9e9f35f6.png)
 大佬，我这个顺序好像还是有问题 ，感觉我给你添了好多麻烦0.0

**Comment by xiyuvi** [comment]
![image](https://user-images.githubusercontent.com/38217058/205239966-a7058e2a-da71-4e4d-a907-6455d2f3a02f.png)

**Comment by CCKNBC** [comment]
@xiyuvi 已修复，希望不要再出现新问题了
