### ISSUE TITLE
0.1.7推送出现逻辑错误导致无法有效推送

### ISSUE THREAD

**Issue by GoodBoyboy666** [Rock-Candy-Tea/hexo-webpushr-notification#8]
在0.1.7版本中由于等待了deploy的进行，导致当插件开始获取服务端上的newpost.json其实是本地已经推送的newpost.json，
以至于使得文章总是“最新”状态而无法正常推送，建议先获取服务端newpost.json再等待deploy最后进行比较推送

**Comment by CCKNBC** [comment]
不知道为什么改成了deployAfter，晚上将发布一个版本改成deployBefore
